// scripts/build-kb.mjs — generate the KB artifacts from the editable master.
// Runs as part of the Vercel build (before the smoke test), so the deployed
// api/_kbdata.js and the public EMBEDDED_KB fallback are ALWAYS freshly derived
// from kb/billfree-kb.json — "forgot to rebuild" drift is structurally impossible.
//
// Master (edit this):  kb/billfree-kb.json  (full, incl. internal records)
// Generated (do not edit):
//   api/_kbdata.js    full KB bundled server-side (never a public static asset)
//   public/index.html EMBEDDED_KB = PUBLIC records only (offline fallback)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const p = (...a) => join(ROOT, ...a);

const die = (msg) => { console.error('BUILD-KB ERROR: ' + msg); process.exit(1); };

const data = JSON.parse(readFileSync(p('kb', 'billfree-kb.json'), 'utf8'));

// ---- validate BEFORE writing anything (don't overwrite good output with bad) ----
const full = data.records;
if (!Array.isArray(full) || full.length === 0) die('records[] missing or empty');
const seen = new Set();
for (const r of full) {
  if (!r || typeof r.id !== 'string') die('a record has no string id');
  if (seen.has(r.id)) die('duplicate id: ' + r.id);
  seen.add(r.id);
  if (r.visibility !== 'public' && r.visibility !== 'internal') {
    die(`record "${r.id}" has visibility "${r.visibility}" (must be "public" or "internal")`);
  }
}

// Explicit, fail-safe public filter: a record reaches the world-readable fallback
// ONLY if it is EXPLICITLY public. Anything else stays out — a typo'd/missing
// visibility can never leak into the public copy.
const publicRecs = full.filter((r) => r.visibility === 'public');
const internalIds = full.filter((r) => r.visibility !== 'public').map((r) => r.id);
console.log(`full=${full.length} public=${publicRecs.length} internal=${internalIds.length}`);

// Escape "</script>" (and "<!--") so KB text can't break out of the inline
// <script> when injected into index.html. JSON.parse / the JS parser restore
// the original characters from the < escape.
const safeJSON = (v) => JSON.stringify(v).replace(/</g, '\\u003c');

// 1) bundled full KB module (server-side only)
const header =
  '// AUTO-GENERATED by scripts/build-kb.mjs from kb/billfree-kb.json — do not edit.\n' +
  '// Bundled into /api/kb (server-side only); contains internal records.\n' +
  'export const KB = ';
writeFileSync(p('api', '_kbdata.js'), header + JSON.stringify(data, null, 2) + ';\n');
console.log('wrote api/_kbdata.js');

// 2) public-only embedded fallback (single line) in index.html
const embed = 'const EMBEDDED_KB = ' + safeJSON(publicRecs) + ';';
const html = readFileSync(p('public', 'index.html'), 'utf8').split('\n');
let n = 0;
for (let i = 0; i < html.length; i++) {
  if (html[i].startsWith('const EMBEDDED_KB = ')) { html[i] = embed; n++; }
}
if (n !== 1) { console.error(`ERROR: expected exactly 1 EMBEDDED_KB line, found ${n}`); process.exit(1); }
writeFileSync(p('public', 'index.html'), html.join('\n'));
console.log('regenerated EMBEDDED_KB (public-only) in public/index.html');

// 3) hard guard: no internal record may reach the public fallback
const leak = publicRecs.filter((r) => internalIds.includes(r.id)).map((r) => r.id);
if (leak.length) { console.error('ERROR: internal record in public embed: ' + leak.join(', ')); process.exit(1); }
console.log('internal (gated):', internalIds.join(', '));
console.log('OK — KB artifacts generated.');
