#!/usr/bin/env python3
"""Build the KB artifacts from the editable master.

Master (edit this):   kb/billfree-kb.json          (full, incl. internal records)
Generated (do not edit):
  - api/_kbdata.js               full KB bundled into /api/kb (server-side only)
  - public/index.html            EMBEDDED_KB = PUBLIC records only (offline fallback)

Run from the repo root:  python scripts/build_kb.py
The full KB is intentionally NOT written under public/, so it is never a
world-readable static asset; internal records reach the browser only via the
secret-gated /api/kb function.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC  = os.path.join(ROOT, "kb", "billfree-kb.json")
KBJS = os.path.join(ROOT, "api", "_kbdata.js")
HTML = os.path.join(ROOT, "public", "index.html")

def main():
    with open(SRC, encoding="utf-8") as f:
        data = json.load(f)

    full = data["records"]
    public = [r for r in full if r.get("visibility") != "internal"]
    internal_ids = sorted(r["id"] for r in full if r.get("visibility") == "internal")
    print(f"full={len(full)} public={len(public)} internal={len(internal_ids)}")

    # 1) bundled full KB module (server-side only)
    header = (
        "// AUTO-GENERATED by scripts/build_kb.py from kb/billfree-kb.json — do not edit.\n"
        "// Bundled into /api/kb (server-side only); contains internal records.\n"
        "export const KB = "
    )
    with open(KBJS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + json.dumps(data, ensure_ascii=False, indent=2) + ";\n")
    print("wrote", os.path.relpath(KBJS, ROOT))

    # 2) public-only embedded fallback (single line) in index.html
    embed = "const EMBEDDED_KB = " + json.dumps(public, ensure_ascii=False) + ";"
    lines = open(HTML, encoding="utf-8").read().split("\n")
    n = 0
    for i, l in enumerate(lines):
        if l.startswith("const EMBEDDED_KB = "):
            lines[i] = embed; n += 1
    if n != 1:
        sys.exit(f"ERROR: expected exactly 1 EMBEDDED_KB line, found {n}")
    with open(HTML, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("regenerated EMBEDDED_KB (public-only) in", os.path.relpath(HTML, ROOT))

    # 3) guard: no internal record may leak into the public embed
    embed_ids = {r["id"] for r in public}
    leak = set(internal_ids) & embed_ids
    if leak:
        sys.exit(f"ERROR: internal records leaked into public embed: {leak}")
    print("internal (gated):", internal_ids)
    print("OK — no internal record in the public fallback.")

if __name__ == "__main__":
    main()
