// AUTO-GENERATED by scripts/build-kb.mjs from kb/billfree-kb.json — do not edit.
// Bundled into /api/kb (server-side only); contains internal records.
export const KB = {
  "version": "2.7",
  "updated": "2026-06",
  "audience": "L1 Technical Support",
  "records": [
    {
      "id": "setup-universal",
      "category": "Core Setup",
      "system": "Universal Utility",
      "type": "setup",
      "symptom": "How does the Universal Setup Utility work / how to install it",
      "cause": "The Universal Utility installs a 'BillFree' virtual printer that intercepts the POS print job, parses it via XPS, writes a PDF + JSON pair into C:\\BillFree\\Data, and uploads them to the BillFree server for WhatsApp + SMS delivery. Because it works at the Windows print layer, it integrates with ANY POS that can print an invoice — no POS-specific plugin needed.",
      "solution": [
        "Prerequisites: complete merchant onboarding first so an ACTIVE Merchant ID (MID) exists (see onboarding). Must be a Windows PC (Windows 7, 8, 10 or 11). On Windows 7 specifically, the installer often shows a .NET Framework error — if that happens, download .NET Framework 4.5 from the same Integration Files portal page, install it, restart the PC, then run the BillFree Universal Setup again.",
        "Log in to the BillFree merchant portal (billfree.in) with the merchant's credentials. You land on the Home dashboard ('Business at a Glance').",
        "Open the Merchant Profile (top-left profile / My Account). It shows Business Details, Store details and Active Features. At the bottom, click 'Download Integration Files'.",
        "On the Integration Files page, download 'BillFree Universal Utility'. This is the BillFreeUniversalSetup Vxx.msi installer (e.g. V10.6). If the PC lacks .NET Framework 4.5, download and install that FIRST from the same page.",
        "The MSI downloads (e.g. BillFreeUniversalSetup V10.6.msi). Open it to launch the installer. Windows 7 — if the installer immediately shows a .NET Framework error: close it, install the .NET 4.5 you downloaded from the portal page, restart the PC, then re-open the MSI.",
        "The 'Welcome to the BillFree Setup Wizard' appears — click Next and complete the wizard with the default options.",
        "The utility installs to C:\\BillFree by default. Confirm the BillFree folder now exists on Local Disk (C:).",
        "Inside C:\\BillFree you'll see the working folders: Data (uploaded PDF+JSON invoices), Doc, Support (printer install scripts), and Temp.",
        "Install the virtual printer driver: open C:\\BillFree\\Support and run the script that matches the OS — InstallPrinter_Win10.bat for Windows 10/11 (use InstallPrinter_Win7.bat on Windows 7). Right-click > Run as administrator.",
        "The script runs rundll32 printui.dll,PrintUIEntry commands: it removes any old 'BillFree' printer, installs the bundled HP driver (from the x64/x86 subfolder), renames it to 'BillFree', and binds it to port lpt1:. Let the command window finish.",
        "In the same Support folder, run SetBillFreeDefaultPrinter.bat to make BillFree the default Windows printer (run SetCustomPaperSize.bat too if a custom paper size is needed).",
        "Open the BillFree Configuration screen and set: Folder Path = C:\\BillFree\\Data; Merchant ID = the merchant's MID (e.g. 28669); Target Printer = BillFree; Print Options = tick 'BillFree' and 'BillFree + Print'; Config Mode = Yes (keep ON for a first-time integration); Forward Print Job = Yes with Fwd Target Printer = the customer's physical printer. Leave the rest at defaults (Enable Logging = Yes, AutoPrintMode = Yes, PDF Mode = Auto). Click Save.",
        "Done. The utility now intercepts every print, converts it to PDF + JSON into C:\\BillFree\\Data, and uploads to the server — the customer receives the digital bill via WhatsApp + SMS. Verify with a test print (see appendix-checklist)."
      ],
      "tags": [
        "install",
        "universal",
        "printer",
        "driver",
        "setup",
        "msi",
        "installprinter",
        "billfree configuration",
        "merchant id",
        "integration files",
        ".net framework"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/setup-universal-1.png",
          "caption": "Step 2 — After login you land on the Home dashboard ('Business at a Glance')."
        },
        {
          "src": "kb-images/setup-universal-2.png",
          "caption": "Step 3 — Open the Merchant Profile: Business & Store details plus Active Features. Click 'Download Integration Files'."
        },
        {
          "src": "kb-images/setup-universal-3.png",
          "caption": "Step 4 — Integration Files page: download 'BillFree Universal Utility' (and .NET Framework 4.5 if not already installed)."
        },
        {
          "src": "kb-images/setup-universal-4.png",
          "caption": "Step 5 — The installer downloads (e.g. BillFreeUniversalSetup V10.6.msi). Open it to begin."
        },
        {
          "src": "kb-images/setup-universal-5.png",
          "caption": "Step 6 — BillFree Setup Wizard welcome screen. Click Next and finish with defaults."
        },
        {
          "src": "kb-images/setup-universal-6.png",
          "caption": "Step 7 — After install, the BillFree folder appears on Local Disk (C:)."
        },
        {
          "src": "kb-images/setup-universal-7.png",
          "caption": "Step 8 — Inside C:\\BillFree: Data, Doc, Support and Temp working folders."
        },
        {
          "src": "kb-images/setup-universal-8.png",
          "caption": "Step 9 — C:\\BillFree\\Support: run InstallPrinter_Win10.bat (or _Win7 on Windows 7) as administrator."
        },
        {
          "src": "kb-images/setup-universal-9.png",
          "caption": "Step 10 — The script runs rundll32 printui.dll commands to install the HP driver, rename it 'BillFree', and bind it to lpt1:."
        },
        {
          "src": "kb-images/setup-universal-10.png",
          "caption": "Step 11 — Run SetBillFreeDefaultPrinter.bat to make BillFree the default Windows printer."
        },
        {
          "src": "kb-images/setup-universal-11.png",
          "caption": "Step 12 — BillFree Configuration: (1) Folder Path, (2) Merchant ID (28669), (3) Target Printer = BillFree, (4) tick BillFree + BillFree + Print, (5) Config Mode = Yes for a first-time integration, (6) Forward Print Job = Yes with Fwd Target Printer, (7) Save."
        }
      ],
      "last_verified": "2026-07",
      "visibility": "public",
      "related": [
        "onboarding",
        "setup-flow",
        "setup-config-popup",
        "setup-printing-types",
        "setup-directory",
        "appendix-checklist",
        "ci-cash-drawer",
        "tally-bitmap-mode"
      ]
    },
    {
      "id": "setup-flow",
      "category": "Core Setup",
      "system": "Universal Utility",
      "type": "reference",
      "symptom": "What is the end-to-end digital bill flow",
      "cause": "POS Software -> BillFree -> Customer WhatsApp pipeline.",
      "solution": [
        "POS prints bill.",
        "BillFree virtual printer captures the print job.",
        "Configuration popup appears.",
        "BillFree converts to PDF + JSON.",
        "Uploads to server.",
        "Digital bill sent to customer via WhatsApp + SMS."
      ],
      "tags": [
        "flow",
        "architecture",
        "pipeline"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "setup-universal",
        "popup-delivery-options"
      ]
    },
    {
      "id": "setup-config-popup",
      "category": "Core Setup",
      "system": "Universal Utility",
      "type": "setup",
      "symptom": "Configuration popup settings (XPS vs Text/DMP)",
      "cause": "Config mode differs by printing type.",
      "solution": [
        "Merchant ID: enter MID (both XPS and Text/DMP).",
        "Target Printer: XPS = select BillFree; Text/DMP = select merchant's printer.",
        "Config Mode: enable on first time only (both).",
        "Forward Print: XPS = enable and select merchant's printer; Text/DMP = N/A.",
        "Outcome: generates a .comp file."
      ],
      "tags": [
        "config",
        "popup",
        "xps",
        "dmp",
        "comp"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/setup-config-popup-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/setup-config-popup-2.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "setup-universal",
        "setup-printing-types",
        "ci-pagesize-a4a5",
        "ci-pagesize-a5",
        "ci-print-cutoff",
        "ci-qr-forward-blank"
      ]
    },
    {
      "id": "setup-printing-types",
      "category": "Core Setup",
      "system": "Universal Utility",
      "type": "reference",
      "symptom": "Mobile number not auto-filling on the popup / which POS printing type am I dealing with (XPS vs Non-XPS vs Text/DMP)",
      "cause": "Whether BillFree can auto-read the bill depends on the POS print output type.",
      "solution": [
        "Windows Printing (XPS): POS outputs XPS-compatible print (text is selectable). Auto-read — content and Mobile No. are extracted automatically.",
        "Windows Printing (Non-XPS): POS outputs an image-based print (text NOT selectable). Manual — BillFree cannot read content; the operator must type the Mobile No. on the popup. This is the usual reason a mobile number does not auto-fill.",
        "Text / DMP Printing: POS outputs raw text (dot-matrix style). Auto-read — BillFree reads the text data for auto extraction.",
        "Diagnosis: if the mobile number never auto-fills, the merchant's POS is almost certainly printing Non-XPS (image). Either switch the POS to a text/XPS-capable format, or accept manual mobile entry."
      ],
      "tags": [
        "xps",
        "non-xps",
        "text",
        "dmp",
        "auto-read",
        "mobile",
        "autofill",
        "printing type",
        "manual entry"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "setup-config-popup",
        "ci-popup-missing",
        "setup-universal",
        "popup-delivery-options",
        "ci-cash-drawer",
        "ci-pagesize-a4a5",
        "ci-pagesize-a5",
        "ci-qr-forward-blank",
        "tally-bitmap-mode"
      ]
    },
    {
      "id": "popup-delivery-options",
      "category": "Core Setup",
      "system": "Universal Utility",
      "type": "reference",
      "symptom": "What do the BillFree popup delivery options mean (Send to BillFree / BillFree + Print / Print Only)",
      "cause": "Every time a print is issued, BillFree pauses the print and shows a popup with delivery choices.",
      "solution": [
        "Mobile Number field: auto-filled if the XPS print has readable text (see setup-printing-types); otherwise enter it manually.",
        "Send to BillFree (Digital Bill): creates PDF+JSON, uploads, customer gets WhatsApp + SMS. No paper print.",
        "BillFree + Print: uploads (customer gets WhatsApp + SMS) AND forwards the print to the merchant's printer.",
        "Print Only: no upload — forwards the print to the merchant's printer only.",
        "Files are taken from C:\\BillFree\\Data\\; the Universal Utility holds the XPS spool file, converts to PDF + JSON, then uploads on selection."
      ],
      "tags": [
        "popup",
        "delivery options",
        "send to billfree",
        "print only",
        "digital bill",
        "whatsapp",
        "sms"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/popup-delivery-options-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "setup-flow",
        "setup-printing-types",
        "ci-cash-drawer"
      ]
    },
    {
      "id": "setup-directory",
      "category": "Core Setup",
      "system": "Universal Utility",
      "type": "reference",
      "symptom": "C:\\BillFree directory structure / what each folder does",
      "cause": "Post-install file layout.",
      "solution": [
        "Data – uploaded invoices (PDF + JSON).",
        "Logs – logs for the last 3 days.",
        "Support – printer scripts (e.g. InstallPrinter_Win10.bat).",
        "comp – config info (MID, printer name).",
        "config.ini – parsing rules for extracting invoice fields.",
        "Reset_BillFree.exe – utility to reset configuration."
      ],
      "tags": [
        "directory",
        "files",
        "logs",
        "comp",
        "config.ini"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "internal",
      "related": [
        "setup-universal"
      ]
    },
    {
      "id": "onboarding",
      "category": "Onboarding",
      "system": "Backend",
      "type": "setup",
      "symptom": "Merchant onboarding & prerequisites / how to register a merchant",
      "cause": "Foundation must be set before any technical work.",
      "solution": [
        "Visit https://billfree.in/site/signup and select 'I am Business'.",
        "Fill: Name & Business Name, Mobile Number, Email & Password, Category & Location, Reference Code.",
        "Verify Mobile No. with OTP.",
        "A unique Merchant ID (MID) is auto-generated (e.g. 28669).",
        "Backend checklist: MID status must be Active; verify correct POS Type is configured (Universal, Busy, Tally, etc.)."
      ],
      "tags": [
        "onboarding",
        "mid",
        "registration",
        "signup"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/onboarding-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "internal",
      "related": [
        "setup-universal"
      ]
    },
    {
      "id": "busy-select-printer",
      "category": "POS Integration",
      "system": "Busy",
      "type": "howto",
      "symptom": "How to select the BillFree printer in Busy",
      "cause": "Different paths for Standard vs Non-Standard formats.",
      "solution": [
        "Standard Format: Administrator > Configuration > Hardware Configuration.",
        "Non-Standard Format: Administrator > Configuration > Invoice/Document Printing > Advanced Printing."
      ],
      "tags": [
        "busy",
        "printer",
        "select"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-select-printer-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-select-printer-2.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "busy-a5",
      "category": "POS Integration",
      "system": "Busy",
      "type": "printing",
      "symptom": "A5 page prints incorrectly in Busy",
      "cause": "Preview and printer settings are mismatched.",
      "solution": [
        "In BillFree printer properties, set page size to A4 (even for A5 documents).",
        "In the customer's main printer properties, also set page size to A4."
      ],
      "tags": [
        "busy",
        "a5",
        "page size",
        "printing"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-twopage"
      ]
    },
    {
      "id": "busy-3inch",
      "category": "POS Integration",
      "system": "Busy",
      "type": "printing",
      "symptom": "3-inch bill not sized correctly in Busy",
      "cause": "Digital bill does not respect the 3-inch printer setting.",
      "solution": [
        "When making the component, set a Custom Width of 80."
      ],
      "tags": [
        "busy",
        "3inch",
        "thermal",
        "width"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "marg-a4instead3"
      ]
    },
    {
      "id": "busy-twopage",
      "category": "POS Integration",
      "system": "Busy",
      "type": "printing",
      "symptom": "Bill prints on two separate pages (content on one, border on another)",
      "cause": "Page size mismatch.",
      "solution": [
        "Set BillFree printer properties page size to A4.",
        "Set customer's main printer properties page size to A4."
      ],
      "tags": [
        "busy",
        "two page",
        "page size"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-a5"
      ]
    },
    {
      "id": "busy-mobile-field",
      "category": "POS Integration",
      "system": "Busy",
      "type": "howto",
      "symptom": "How to add Mobile No. field in Busy (Standard Format)",
      "cause": "The field is an optional setting.",
      "solution": [
        "Administrator > Configuration > Invoice/Document Printing > Standard > Sales Invoice.",
        "Set 'Print Party Details' to Y.",
        "In the popup, check 'Print Mobile No.'."
      ],
      "tags": [
        "busy",
        "mobile",
        "field",
        "standard"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "busy-email",
      "category": "Email Integration",
      "system": "Busy",
      "type": "setup",
      "symptom": "How to configure Busy Email (Gmail) integration",
      "cause": "Email-based integration requires Gmail App Password and matching MID config.",
      "solution": [
        "Prereqs: Gmail ID must match the user MID; POS Type 'Busy' selected in BillFree backend; 2-Step Verification ON in Google account.",
        "Generate Google App Password: Gmail > Manage Google Account > Security > App Passwords. Name it (e.g. 'Busy_Email'), generate, copy the 16-char password.",
        "Busy: Administration > Configuration > Email Configuration. Check 'Send Directly' and 'PDF+XML Attachment' (invoice only).",
        "SMTP Server: smtp.gmail.com | Username: merchant Gmail ID | Password: paste 16-char App Password.",
        "From: Merchant Name | Reply To: Merchant Email ID.",
        "Administration > Configuration > Vouchers Configuration > Sales > Main > Voucher Configuration.",
        "Set 'Separate Billing Details' = Y; 'Specify key field' = Mobile No.; 'Send Email After Saving' = Y.",
        "Email format: Standard. Prompt for sending email: Y (set N to auto-send). Show email options: Y. Send to Party: Y. BCC To Self: Y. Self-Email ID: bills@billfree.in."
      ],
      "tags": [
        "busy",
        "email",
        "gmail",
        "smtp",
        "app password"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-email-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-email-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-email-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-email-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-email-5.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-email-6.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-email-7.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-email-8.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "tally-mobile-tdl",
      "category": "POS Integration",
      "system": "Tally",
      "type": "howto",
      "symptom": "How to add Mobile No. field in Tally using TDL (Standard Format)",
      "cause": "TDL file is required to add the field.",
      "solution": [
        "F1 Help > TDLs & Add Ons > Manage Local TDLs.",
        "Select 'Select from Drive'.",
        "Load TDL: BillFree > BillFreeUniTallyPrime.tcp.",
        "Note: will not work on customized Tally invoices. For those, use Universal Setup with manual Mobile No. entry, or request a custom TDL from BillFree."
      ],
      "tags": [
        "tally",
        "tdl",
        "mobile",
        "field"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "tally-select-printer",
      "category": "POS Integration",
      "system": "Tally",
      "type": "howto",
      "symptom": "How to select the BillFree printer in Tally",
      "cause": "Printer is selected from the print configuration menu.",
      "solution": [
        "From Tally Home, type DAS (Display Account Books > Sales Register).",
        "Select any bill and press Ctrl + P.",
        "In the print config popup, select Printer on the right side.",
        "Choose the BillFree printer."
      ],
      "tags": [
        "tally",
        "printer",
        "select",
        "das"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "tally-bitmap-mode"
      ]
    },
    {
      "id": "tally-billtransfer",
      "category": "Setup Utility",
      "system": "Tally",
      "type": "setup",
      "symptom": "How to install Tally BillTransfer utility",
      "cause": "BillTransfer enables direct Tally integration without a virtual printer.",
      "solution": [
        "Install BillTransferSetUpWin10 V10.msi from the backend.",
        "Go to C:\\BillFree and run billfree.exe; enter Merchant ID and save.",
        "Create a shortcut of billfree.exe.",
        "Open Run (Win+R), type 'shell:startup', paste the shortcut into the Startup folder.",
        "Load TDL: F1 Help > TDLs & Add Ons > F4 Manage Local TDL. Set 'Load TDLs on startup' = Yes.",
        "Select from Drive: C:\\BillFree\\Billtransfer.tcp (Tally ERP) OR BilltransferPrime.tcp (Tally Prime, download separately from backend).",
        "Ensure it shows as LOADED.",
        "Type DAS on the main screen, open any bill, enter Mobile No. in the address/ledger of the invoice, save.",
        "Popup 'Send to BillFree' appears; press Enter to export PDF+JSON to \\Data folder and upload to server -> customer."
      ],
      "tags": [
        "tally",
        "billtransfer",
        "tdl",
        "startup",
        "das"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/tally-billtransfer-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-5.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-6.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-8.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-9.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-7.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-10.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-billtransfer-11.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "tally-api-tdl",
      "category": "API Integration",
      "system": "Tally",
      "type": "setup",
      "symptom": "How to configure Tally API TDL plugin (BillFreeTallyApi.tcp)",
      "cause": "API push model via TDL addon.",
      "solution": [
        "F1 Help > TDLs & Add Ons > F4 Manage Local TDL. Set 'Load TDLs on startup' = Yes.",
        "Select from Drive: C:\\BillFree\\BillFreeTallyApi.tcp (path may differ in Tally Cloud). Ensure LOADED.",
        "Sidebar > F6 Addon Features. Enable BillFree addon = Yes. Press Esc.",
        "Gateway of Tally > BillFree > Login. Enter merchant BillFree credentials, Accept = Yes. Wait for 'Login Successfully'.",
        "After login a setup plugin downloads. Wait for 'Installation Done' popup.",
        "Test: create a bill, enter Mobile No. in Phone No. field, save. Popup 'Do you want to send invoice to BillFree' -> Yes."
      ],
      "tags": [
        "tally",
        "api",
        "tdl",
        "addon",
        "plugin"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/tally-api-tdl-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-api-tdl-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-api-tdl-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-api-tdl-6.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-api-tdl-5.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-api-tdl-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-api-tdl-7.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/tally-api-tdl-8.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "gofrugal-select-printer",
      "category": "POS Integration",
      "system": "GoFrugal",
      "type": "howto",
      "symptom": "How to select the BillFree printer in Go Frugal",
      "cause": "Selected via preview > printer settings.",
      "solution": [
        "Click the printer symbol (top left).",
        "Go to bills list, select a bill, click Preview.",
        "In preview, click the Printer Setting icon.",
        "Select the BillFree printer."
      ],
      "tags": [
        "gofrugal",
        "printer",
        "select",
        "preview"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "gofrugal-thermal",
        "gofrugal2-select"
      ]
    },
    {
      "id": "gofrugal-thermal",
      "category": "POS Integration",
      "system": "GoFrugal",
      "type": "printing",
      "symptom": "Long bill / thermal printer issue in Go Frugal",
      "cause": "Printer type set incorrectly.",
      "solution": [
        "Printer Setting menu > Printer Type.",
        "Change from 'Thermal' to Laser Printer or Normal Printer.",
        "Select the BillFree printer."
      ],
      "tags": [
        "gofrugal",
        "thermal",
        "laser",
        "printer type"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "gofrugal-select-printer"
      ]
    },
    {
      "id": "gofrugal2-select",
      "category": "POS Integration",
      "system": "GoFrugal",
      "type": "howto",
      "symptom": "GoFrugal printer change / selection via Bill List reprint",
      "cause": "Printer changed from preview screen.",
      "solution": [
        "Open Bill List / Reprint; click the printer icon.",
        "Apply filters (Date/Amount/Bill No) if needed and click the desired bill row.",
        "Press F10 (Preview) or the Print Preview icon.",
        "Click the Printer Setting icon, then Printer Type.",
        "Change printer to BillFree and apply."
      ],
      "tags": [
        "gofrugal",
        "printer",
        "reprint",
        "f10"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/gofrugal2-select-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/gofrugal2-select-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/gofrugal2-select-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/gofrugal2-select-4.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "gofrugal-select-printer"
      ]
    },
    {
      "id": "marg-config",
      "category": "POS Integration",
      "system": "Marg",
      "type": "setup",
      "symptom": "How to configure Marg",
      "cause": "Printer mapped to LPT1.",
      "solution": [
        "Masters > Marg Setup > Printer Set Up > Change Options.",
        "Set LPT1 to YES.",
        "On the alert, select BillFree and click OK; press Esc.",
        "On 'Make Printer Default', select Yes.",
        "Print a sample file to test."
      ],
      "tags": [
        "marg",
        "lpt1",
        "printer",
        "config"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/marg-config-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/marg-config-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "genesys-api"
      ]
    },
    {
      "id": "marg-leftcut",
      "category": "POS Integration",
      "system": "Marg",
      "type": "printing",
      "symptom": "Print cut from left side in 3-inch format (Marg)",
      "cause": "Borderless/paper type not set.",
      "solution": [
        "BillFree Printer Setting > General Option > Preferences.",
        "Set Borderless ON; Paper type = HP Photo papers.",
        "Repeat the same in Advanced Option.",
        "Print to verify."
      ],
      "tags": [
        "marg",
        "3inch",
        "borderless",
        "left cut"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "ci-mfp-noprint",
        "ci-qr-forward-blank"
      ]
    },
    {
      "id": "marg-a4instead3",
      "category": "POS Integration",
      "system": "Marg",
      "type": "printing",
      "symptom": "Digital bill appears in A4 instead of 3-inch (Marg)",
      "cause": "Width not set.",
      "solution": [
        "On the BillFree Configuration popup, set a Custom Width of 80.",
        "Verify the bill now appears in correct 3-inch format."
      ],
      "tags": [
        "marg",
        "3inch",
        "a4",
        "width"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-3inch",
        "ci-pagesize-a4a5"
      ]
    },
    {
      "id": "marg-api",
      "category": "API Integration",
      "system": "Marg",
      "type": "setup",
      "symptom": "How to activate BillFree in Marg ERP (EXE utility + Self-Designed Report method)",
      "cause": "Marg ERP integrates BillFree via a custom Self-Designed Report that runs CONFIG.EXE. An Auth Key (from BillFree backend) and an Admin Key (generated at kridhaverse.com) are both required for activation.",
      "solution": [
        "Download required files: open www.kridhaverse.com, click the BILLFREE menu, go to the Download section. Download all four files: CONFIG.EXE, DIGITALBILL.EXE, REWARDS.EXE, and BILLFREE SETUP EXE.",
        "Create a folder named BILLFREE on your PC and place all four downloaded files inside it.",
        "Copy the entire BILLFREE folder into the Marg ERP installation directory (typically C:\\MARGERP\\). The resulting path should be C:\\MARGERP\\BILLFREE\\.",
        "In Marg ERP go to: Masters > Marg Setups > Advance Features > Self Designed Reports.",
        "Create a new Self-Designed Report: enter Report No. = 01 and Name = .BILL FREE SETTING.",
        "In Report Self Development, select A) OPEN PROGRAM. In the 'Set Your Commands' editor (Edit > Marg > Format), type the command: DO BILLFREE\\CONFIG.EXE. Press CTRL+W to save the code, then Exit.",
        "Restart Marg: Close Marg ERP → Close Marg Server → Start Marg ERP again.",
        "Open Bill Free Settings: Daily Reports > Self Designed Reports > 01 - BILL FREE SETTING.",
        "Select A) ACTIVATE BILL FREE to activate the core integration.",
        "Activate additional modules as required: select B) ACTIVATE DIGITAL BILL (enables digital bill delivery to customers); select C) ACTIVATE REWARD (enables loyalty/rewards).",
        "Select E) REGISTER BILL FREE AUTH KEY to begin key registration.",
        "Generate your Admin Key: open www.kridhaverse.com > BILLFREE menu > click 'GENERATE BILL FREE ADMIN KEY', fill in the merchant details, and generate the key. Note the Admin Serial No. displayed (e.g. ST2474446991JN).",
        "Back in Marg Bill Free Settings (option E), enter the Auth Key (provided by BillFree backend) in the 'ENTER THE AUTH KEY' field, then enter the Admin Key generated in the previous step. Click Update.",
        "Final restart: Close Marg ERP → Close Marg Server → Start Marg Server → Start Marg ERP.",
        "Verify activation: BillFree, Digital Bill, and Rewards should all show as Activated. Test by generating a bill — the customer should receive a digital bill via WhatsApp/SMS."
      ],
      "tags": [
        "marg",
        "api",
        "setup",
        "config.exe",
        "self designed reports",
        "auth key",
        "admin key",
        "kridhaverse",
        "activation",
        "digital bill",
        "rewards",
        "billfree setup exe"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/marg-api-1.jpg",
          "caption": "Complete 15-step BillFree activation guide for Marg ERP — from file download to final restart"
        }
      ],
      "last_verified": "2026-06",
      "visibility": "public",
      "related": [
        "genesys-api",
        "ci-qr-forward-blank"
      ]
    },
    {
      "id": "zorder-select",
      "category": "POS Integration",
      "system": "Zorder",
      "type": "howto",
      "symptom": "How to select the printer in Zorder",
      "cause": "Format-to-printer mapping in Options.",
      "solution": [
        "Zorder > Tools > Options (Printer Settings).",
        "Click Printer Settings; you'll see the list of formats and selected printers.",
        "Select the format, select the BillFree printer and page size.",
        "Test by giving a print command in Zorder."
      ],
      "tags": [
        "zorder",
        "printer",
        "select",
        "format"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/zorder-select-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zorder-select-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zorder-select-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zorder-select-4.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "shopper-select",
      "category": "POS Integration",
      "system": "Shopper",
      "type": "howto",
      "symptom": "How to select the printer in Shopper",
      "cause": "Print Engine Configuration per transaction.",
      "solution": [
        "Open Shopper logged in as admin/main user.",
        "Print Engine Configuration > Configure Specific Transaction.",
        "Sales > Sales Transaction > click the selected template/format.",
        "Click Parameters > printer selection setting > select BillFree printer, then Save (Windows printing).",
        "For text printing: select their printer and choose DOS Printing."
      ],
      "tags": [
        "shopper",
        "printer",
        "print engine",
        "dos"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/shopper-select-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/shopper-select-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/shopper-select-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/shopper-select-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/shopper-select-5.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "logics-select",
      "category": "POS Integration",
      "system": "Logics",
      "type": "howto",
      "symptom": "How to select the printer in Logics ERP",
      "cause": "Printer changed from Print Designer file settings.",
      "solution": [
        "Open Logics with super/admin user.",
        "Click Continuous Folder > Sale Bill - Print Designer.",
        "Click Search Bill, select Sales Bill.",
        "Click the Search icon, select any bill, press OK.",
        "Click Refresh and Confirm.",
        "File > Printer Settings — change the printer here."
      ],
      "tags": [
        "logics",
        "printer",
        "print designer",
        "erp"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/logics-select-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/logics-select-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/logics-select-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/logics-select-4.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "wizapp-phase1",
      "category": "POS Integration",
      "system": "WizApp",
      "type": "setup",
      "symptom": "WizApp printer selection — Phase 1: format init & Crystal Reports dependency",
      "cause": "WizApp uses Crystal Reports (.rpt) templates.",
      "solution": [
        "Open WizApp POS, log in with admin credentials.",
        "Billing screen > print options to view report formats.",
        "Minimize to desktop, right-click the WizApp shortcut > Open file location.",
        "Open the 'Reports' subfolder, then the 'Sale' subdirectory.",
        "Copy the BillFree template 'BF_Thermal_3in.rpt' into this directory.",
        "If Crystal Reports runtime is missing, download & install SAP Crystal Reports 2016 (e.g. CR201609P) as Administrator (trial license key from SAP site).",
        "Launch SAP Crystal Reports, open BF_Thermal_3in.rpt.",
        "File > Page Setup: disable 'No Printer' flag, bind 'BillFree' via Printer Options. OK and Save."
      ],
      "tags": [
        "wizapp",
        "crystal report",
        "rpt",
        "thermal",
        "sap"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/wizapp-phase1-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-5.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-6.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-7.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-8.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-9.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-10.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-11.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase1-2.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "wizapp-phase2",
      "category": "POS Integration",
      "system": "WizApp",
      "type": "setup",
      "symptom": "WizApp Phase 2: manual report configuration (.rdlc vs .rpt)",
      "cause": "Bill format unreadable or in .rdlc; add a readable .rpt manually.",
      "solution": [
        "In the WizApp print dialogue, expose the 'Add Report' parameters group and invoke 'Add'.",
        "Title = 'BF_Thermal_3in'; Name = 'BF_Thermal_3in.rpt' (map identically).",
        "Save by clicking 'Set'.",
        "Confirm the 'Are you Sure to Save Changes?' prompt.",
        "Check the 'Default' checkbox for this new mapping. All billing prints now route through BillFree."
      ],
      "tags": [
        "wizapp",
        "rdlc",
        "rpt",
        "report",
        "default"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/wizapp-phase2-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase2-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase2-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/wizapp-phase2-4.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "drishti-select",
      "category": "POS Integration",
      "system": "Drishti",
      "type": "howto",
      "symptom": "How to select the printer in Drishti",
      "cause": "Uses .rpt (Crystal Report) in most cases.",
      "solution": [
        "Install SAP Crystal Report first if not present.",
        "Open Drishti > Tools > Printer Settings, select BillFree."
      ],
      "tags": [
        "drishti",
        "crystal report",
        "rpt",
        "printer"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "monark-select"
      ]
    },
    {
      "id": "monark-select",
      "category": "POS Integration",
      "system": "Monark",
      "type": "howto",
      "symptom": "How to select the printer in Monark",
      "cause": "Uses .rpt (Crystal Report) in most cases.",
      "solution": [
        "Install SAP Crystal Report first if not present.",
        "Open Monark > Tools > Printer Settings, select BillFree."
      ],
      "tags": [
        "monark",
        "crystal report",
        "rpt",
        "printer"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "drishti-select"
      ]
    },
    {
      "id": "eshopaid-identify",
      "category": "POS Integration",
      "system": "Wondersoft eShopaid",
      "type": "howto",
      "symptom": "Wondersoft eShopaid — identify printing type (Win vs Dos)",
      "cause": "Integration path depends on PrinterType in Printer Manager.",
      "solution": [
        "eShopaid is web-based (localhost:8020/mshopaid/). Supports DOS (Text/DMP) and Windows printing.",
        "In the billing screen, check the Printer Manager panel (right side).",
        "PrinterType = 'Win' -> select BillFree as PrinterName.",
        "PrinterType = 'Dos' -> use merchant's native printer (BillFree captures via text interception)."
      ],
      "tags": [
        "eshopaid",
        "wondersoft",
        "win",
        "dos",
        "printer type"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/eshopaid-identify-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "eshopaid-windows",
      "category": "POS Integration",
      "system": "Wondersoft eShopaid",
      "type": "howto",
      "symptom": "eShopaid Path A — Windows printing, select BillFree printer",
      "cause": "PrinterType = Windows.",
      "solution": [
        "Open Printer Manager panel (right of billing screen), find PrinterName dropdown.",
        "Select BillFree from the list.",
        "Settings: Print Format Type = Custom; PrinterType = Win; Where To Print = Main; PrinterName = BillFree; Print Format = appropriate format."
      ],
      "tags": [
        "eshopaid",
        "wondersoft",
        "windows",
        "printer"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "acme-printer",
      "category": "POS Integration",
      "system": "Acme",
      "type": "howto",
      "symptom": "Acme (eShopaid variant) — change printer via Document Printing Format Setting",
      "cause": "Acme variants use the A15 Document Printing Format Setting module.",
      "solution": [
        "Software Management > Customization And Configuration > A15 – Document Printing Format Setting.",
        "Click 'Set Format Against Document'. Doc Type = Sales Document > 01 – Sales Bill.",
        "In BrowsePrintingFormatMaster grid, click the invoice format row in use.",
        "Click the Printer column > 'Update Printing Format Select Printer' popup > select BillFree > OK.",
        "Verify: create a test Sales Bill, click Print, BillFree popup appears, Send to BillFree, confirm WhatsApp/SMS."
      ],
      "tags": [
        "acme",
        "eshopaid",
        "a15",
        "printer",
        "document format"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/acme-printer-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/acme-printer-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/acme-printer-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/acme-printer-4.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "arnon-printer",
      "category": "POS Integration",
      "system": "Arnon",
      "type": "howto",
      "symptom": "How to select printer and bind custom template in Arnon POS",
      "cause": "Uses .rpt (Crystal Report).",
      "solution": [
        "Install SAP Crystal Report if not present.",
        "Locate Arnon Reports folder (right-click shortcut > Open file location > Reports, e.g. C:\\Arnon\\Reports\\ or D:\\Arnon\\reports\\).",
        "Open PrintInvGST.rpt in SAP Crystal Reports.",
        "File > Page Setup: uncheck 'No Printer', select 'BillFree' printer, set paper size, save the template.",
        "Open Arnon POS, log in, sales print options > choose the new template as active format, set printer name to 'BillFree', save.",
        "Verify: print a test invoice; BillFree popup appears."
      ],
      "tags": [
        "arnon",
        "crystal report",
        "rpt",
        "template",
        "printer"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/arnon-printer-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/arnon-printer-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/arnon-printer-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/arnon-printer-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/arnon-printer-5.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "api-flow",
      "category": "API Integration",
      "system": "General",
      "type": "reference",
      "symptom": "API request flow / internal breakdown",
      "cause": "API integrations need no file install — POS pushes invoice JSON.",
      "solution": [
        "POS sends POST request; BillFree validates MID active and token valid.",
        "Parsing engine validates fields; BillFree creates PDF + JSON.",
        "Invoice stored in merchant DB.",
        "Delivery engine fires WhatsApp/SMS; status updated in merchant dashboard."
      ],
      "tags": [
        "api",
        "flow",
        "post",
        "token",
        "mid"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "zoho-api",
      "category": "API Integration",
      "system": "Zoho",
      "type": "setup",
      "symptom": "Zoho Inventory API integration (Webhook + Workflow Rule)",
      "cause": "Zoho sends invoice data to BillFree when invoice is marked Paid. No plugin needed.",
      "solution": [
        "Part A — Webhook: Zoho Inventory > Settings > Automation > Workflow Actions > Webhooks > + New Webhook.",
        "Configure: Name='BillFree Integration', Module='Invoice', HTTP Method=POST, URL='https://billfree.in/zoho/index', Parameter Key='auth_token', Parameter Value=merchant's Auth Token from BillFree dashboard.",
        "IMPORTANT: auth_token is unique per merchant — always get it from the merchant's BillFree dashboard. Never use a placeholder.",
        "Review default JSON payload (Content-Type: application/json), Save.",
        "Part B — Workflow Rule: Settings > Automation > Workflow Rules > + New. Module=Invoice, Name=BillFree.",
        "Execution: Workflow Type=Event Based; Action Type=Created or Edited; Execute when any field is updated; Execute when record is 'Edited for the first time' (fires once, prevents duplicates).",
        "Criteria (1 AND 2): Invoice# is Invoice#; Status is Paid. The 'Status is Paid' criterion is essential — without it BillFree fires on every edit including drafts.",
        "Immediate Action: Add Actions > Webhooks > select 'BillFree Integration' > Associate.",
        "Save the rule; status shows Active.",
        "Test: create invoice (Draft) > mark Paid > webhook fires > customer gets WhatsApp+SMS. Verify via Settings > Workflow Logs."
      ],
      "tags": [
        "zoho",
        "api",
        "webhook",
        "workflow",
        "auth_token",
        "paid"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/zoho-api-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-5.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-6.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-8.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-9.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-10.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-11.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-7.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/zoho-api-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "quickbill-api",
      "category": "API Integration",
      "system": "QuickBill",
      "type": "setup",
      "symptom": "QuickBill API integration & discount config",
      "cause": "Auth-token based loyalty enablement.",
      "solution": [
        "Log in to QuickBill POS as admin/super-user.",
        "System > Communication Settings > select BillFree.",
        "Check 'Enable BillFree Loyalty Program', input merchant's Access Token, Save (F10).",
        "Discount behaviour: System Configuration > Sales. 'Bill Level Discount' = 'Based on Definition'; 'Item Level Discount Applicability' = 'Based on Item Level Discount Setting'. Save (F10).",
        "Manual discount (troubleshooting, if unable to add discount): Masters > Discounts/Factors > Bill Level Discount. Create/edit a definition (e.g. 'manual discount'), set applicability/period/type/rate, save."
      ],
      "tags": [
        "quickbill",
        "api",
        "access token",
        "discount",
        "loyalty"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/quickbill-api-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/quickbill-api-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/quickbill-api-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/quickbill-api-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/quickbill-api-5.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/quickbill-api-6.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "genesys-api",
      "category": "API Integration",
      "system": "Genesys",
      "type": "setup",
      "symptom": "Genesys API integration (Auth Token push model)",
      "cause": "Auth-token push of invoice data.",
      "solution": [
        "Log in to Genesys POS with admin/super credentials.",
        "System > Integration Modules > Communication Settings.",
        "Select BillFree.",
        "Paste the merchant-specific BillFree Auth Token.",
        "Save and print a test bill; confirm digital invoice delivered."
      ],
      "tags": [
        "genesys",
        "api",
        "auth token",
        "push"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "marg-config",
        "marg-api"
      ]
    },
    {
      "id": "petpooja-api",
      "category": "API Integration",
      "system": "PetPooja",
      "type": "reference",
      "symptom": "PetPooja API integration",
      "cause": "Auth-token based API integration.",
      "solution": [
        "NOTE: The source guide lists PetPooja API in its contents but ships no step body; the steps below are the standard auth-token push pattern and are UNVERIFIED. Confirm exact menu paths with the PetPooja integration before relying on this.",
        "Auth-token based push: obtain the merchant Auth Token from the BillFree dashboard.",
        "In PetPooja's BillFree / communication settings, enter the merchant Auth Token.",
        "Save and print a test bill; confirm the digital bill is delivered."
      ],
      "tags": [
        "api",
        "auth token",
        "petpooja",
        "unverified"
      ],
      "level": "L1",
      "images": [],
      "visibility": "internal"
    },
    {
      "id": "busy-api-install",
      "category": "API Integration",
      "system": "Busy",
      "type": "setup",
      "symptom": "Busy API / Add-on installation (Part 1)",
      "cause": "DLL-based add-on install.",
      "solution": [
        "Download latest API file from BillFree backend and unzip.",
        "Check POS format: Administrator > voucher series config > select voucher series > voucher configuration > 'Enable advanced POS data entry'. Y = POS billing format, N = standard/normal.",
        "Copy files into C:\\Busywin\\System\\: AddOn_BillFree.dll, AddOn_Registerdll_RunAsAdmin.bat, BillFree.bcd (BillFree.bcd used for both POS and Standard).",
        "Configure AddOns.ini in C:\\Busywin\\System\\. If it exists, add line 'AddOn_BillFree; BillFree' (don't touch other lines). If not, create new text doc with that line and save as 'Addons.ini' (Save as type: All files).",
        "Register DLL: open CMD as Administrator, run: regsvr32 \"C:\\Busywin\\System\\AddOn_BillFree.dll\". OR right-click AddOn_Registerdll_RunAsAdmin.bat > Run as Administrator > Run > Yes.",
        "Confirmation: 'DLL registered successfully.'"
      ],
      "tags": [
        "busy",
        "api",
        "dll",
        "regsvr32",
        "addon",
        "addons.ini"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-api-install-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-install-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-install-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-install-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-install-5.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-api-bcd",
        "busy-api-billship",
        "busy-api-vsg",
        "busy-api-config",
        "busy-api-discount",
        "busy-api-digitalbill"
      ]
    },
    {
      "id": "busy-api-bcd",
      "category": "API Integration",
      "system": "Busy",
      "type": "setup",
      "symptom": "Busy API Part 2 — restore custom validation (BillFree.bcd)",
      "cause": "Custom validation must be restored in BUSY.",
      "solution": [
        "Ensure BillFree.bcd is in C:\\Busywin\\System\\.",
        "Open BUSY, open the company.",
        "Administration > Utilities > Customization > Custom Validation > Restore Custom Validation.",
        "Browse and select BillFree.bcd, click Restore.",
        "Default password: obtain from L2 / the BillFree secrets vault (never stored in this KB).",
        "Design custom validation: select BillFree/BillFree POS format; copy the 8-digit license no. from the busy file (C:\\BusyWin) and paste into the dongle no. field; Save. (Also disables the demo-mode popup after saving a bill.)"
      ],
      "tags": [
        "busy",
        "api",
        "bcd",
        "custom validation",
        "dongle",
        "password"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-api-bcd-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-3.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-6.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-5.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-7.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-8.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-9.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-10.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-11.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-12.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-bcd-13.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "internal",
      "related": [
        "busy-api-install",
        "busy-api-billship",
        "busy-api-vsg",
        "busy-api-config",
        "busy-api-discount",
        "busy-api-digitalbill"
      ]
    },
    {
      "id": "busy-api-billship",
      "category": "API Integration",
      "system": "Busy",
      "type": "setup",
      "symptom": "Busy API Part 3 — enable separate billing/shipping (mobile number required)",
      "cause": "Mobile number capture requires separate billing details.",
      "solution": [
        "Administration > Configuration > Voucher Series Configuration > Sale > Voucher Configuration.",
        "Set 'Separate Billing/Shipping Details' = Y. Save."
      ],
      "tags": [
        "busy",
        "api",
        "billing",
        "shipping",
        "mobile"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-api-billship-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-billship-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-billship-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-billship-3.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-api-install",
        "busy-api-bcd",
        "busy-api-vsg",
        "busy-api-config",
        "busy-api-discount",
        "busy-api-digitalbill"
      ]
    },
    {
      "id": "busy-api-vsg",
      "category": "API Integration",
      "system": "Busy",
      "type": "setup",
      "symptom": "Busy API Part 4 — voucher series group config (multiple stores)",
      "cause": "Restrict BillFree trigger to specific stores.",
      "solution": [
        "Administration > Configuration > Voucher Series Configuration > Sale > Voucher Series Group Management.",
        "Create a new Voucher Series Group named 'BillFree'.",
        "Add required Sale Voucher Series to this group; save.",
        "Only voucher series in this group will trigger the BillFree Loyalty form during billing."
      ],
      "tags": [
        "busy",
        "api",
        "voucher series group",
        "multi store"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-api-vsg-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-vsg-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-vsg-4.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-vsg-3.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-api-install",
        "busy-api-bcd",
        "busy-api-billship",
        "busy-api-config",
        "busy-api-discount",
        "busy-api-digitalbill"
      ]
    },
    {
      "id": "busy-api-config",
      "category": "API Integration",
      "system": "Busy",
      "type": "setup",
      "symptom": "Busy API Part 5 — add-on configuration",
      "cause": "Final add-on config screen.",
      "solution": [
        "Open AddOn > BillFree to get the BillFree Configuration screen.",
        "Enable BillFree: Yes.",
        "BillFree Username & Password: enter provided credentials. Click Verify, then OK.",
        "Store Identifier: Voucher Series.",
        "BillFree Discount Ledger: BillFree Discount.",
        "Reward position in POS BS: 1.",
        "Click Save > OK > OK. A confirmation msg on creating/modifying a bill means setup is integrated."
      ],
      "tags": [
        "busy",
        "api",
        "config",
        "ledger",
        "username"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-api-config-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-config-2.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-config-3.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-api-install",
        "busy-api-bcd",
        "busy-api-billship",
        "busy-api-vsg",
        "busy-api-discount",
        "busy-api-digitalbill"
      ]
    },
    {
      "id": "busy-api-discount",
      "category": "API Integration",
      "system": "Busy",
      "type": "howto",
      "symptom": "Busy API Part 6 — applying BillFree discount during billing",
      "cause": "Hotkey applies the discount.",
      "solution": [
        "While creating a new Sales Bill, press Alt + 3. BillFree discount is applied."
      ],
      "tags": [
        "busy",
        "api",
        "discount",
        "alt+3"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-api-install",
        "busy-api-bcd",
        "busy-api-billship",
        "busy-api-vsg",
        "busy-api-config",
        "busy-api-digitalbill"
      ]
    },
    {
      "id": "busy-api-digitalbill",
      "category": "API Integration",
      "system": "Busy",
      "type": "howto",
      "symptom": "Busy API Part 7/8 — process to digital bill & loyalty/rewards flow",
      "cause": "Mobile no. + send confirmation drives delivery and loyalty.",
      "solution": [
        "While creating a new bill, enter Mobile No. after saving the sale voucher/bill.",
        "Popup 'Do you want to send bill to customer' > Yes. Confirmation: 'Bill sent to the customer's phone'.",
        "Loyalty window 'BillFree Loyalty and Rewards' appears on saving a Sales Voucher.",
        "Enter Customer Contact Number; system shows available loyalty points.",
        "Redemption options: Coupon (shows linked coupons), Points (shows max discount), Referral (shows referrer number + max referral discount).",
        "System displays applicable loyalty scheme details.",
        "OTP sent to customer's mobile; enter OTP to verify. On success, discount applied automatically and the claim is applied to the bill."
      ],
      "tags": [
        "busy",
        "api",
        "digital bill",
        "loyalty",
        "otp",
        "rewards",
        "redemption"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/busy-api-digitalbill-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/busy-api-digitalbill-2.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "busy-api-install",
        "busy-api-bcd",
        "busy-api-billship",
        "busy-api-vsg",
        "busy-api-config",
        "busy-api-discount"
      ]
    },
    {
      "id": "ci-net7",
      "category": "Common Issue",
      "system": "Windows",
      "type": "error",
      "level": "L1",
      "symptom": ".NET Framework fails to install on Windows 7 (hresult 0xc8000222)",
      "cause": "Windows Update service is blocking the installation.",
      "solution": [
        "Open CMD as Administrator.",
        "Run: net stop WuAuServ",
        "Run: ren %windir%\\SoftwareDistribution SoftwareDistribution.old",
        "Run: net start WuAuServ",
        "Retry the .NET installation."
      ],
      "tags": [
        "dotnet",
        ".net",
        "windows 7",
        "0xc8000222",
        "install"
      ],
      "images": [
        {
          "src": "kb-images/ci-net7-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "ci-util-install",
      "category": "Common Issue",
      "system": "Windows",
      "type": "error",
      "symptom": "BillFree Utility installation fails",
      "cause": "Installer popup missing, interrupted install, or full C: drive.",
      "solution": [
        "Cause 1 (no popup): disable antivirus/firewall temporarily; Task Manager > Details > end any msiexec.exe; right-click installer > Run as Administrator.",
        "Cause 2 ('installation was interrupted'): run installer as Administrator; if persists use 'Microsoft Install and Uninstall Troubleshooter' to clean partial installs.",
        "Cause 3 (C: drive full): run Disk Cleanup to free space, or install to a different drive (e.g. D:); retry."
      ],
      "tags": [
        "install",
        "installer",
        "msiexec",
        "disk full",
        "antivirus"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "ci-printer-install",
      "category": "Common Issue",
      "system": "Printer",
      "type": "error",
      "symptom": "BillFree printer installation fails",
      "cause": "Spooler stopped, wrong bitness, server compatibility, or Protected Print Mode.",
      "solution": [
        "Cause 1 (Print Spooler not running): services.msc > Print Spooler > right-click > Restart.",
        "Cause 2 (32/64-bit mismatch): verify OS bitness in System Properties; use the matching installer.",
        "Cause 3 (Windows Server compat): confirm the Server version (2012/2016) is supported by the driver.",
        "Cause 4 (Protected Print Mode): gpedit.msc > 'Point and Print Restrictions' > disable or add exception."
      ],
      "tags": [
        "printer",
        "spooler",
        "32-bit",
        "64-bit",
        "server",
        "gpedit"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "ci-printer-props",
      "category": "Common Issue",
      "system": "Printer",
      "type": "error",
      "symptom": "Error: 'Printer properties cannot be displayed. The data area passed to a system call is too small.'",
      "cause": "Corrupted printer driver installation.",
      "solution": [
        "Control Panel > Devices and Printers > remove the BillFree printer.",
        "Start Menu > type 'Print Server Properties' > open.",
        "Drivers tab > select BillFree driver > Remove ('Remove driver and driver package').",
        "Restart the computer.",
        "Re-install the BillFree printer.",
        "If it persists, set the BillFree printer to Online instead of Offline."
      ],
      "tags": [
        "printer",
        "driver",
        "data area",
        "corrupt",
        "reinstall"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "ci-cash-drawer"
      ]
    },
    {
      "id": "ci-cash-drawer",
      "category": "Common Issue",
      "system": "Printer",
      "type": "printing",
      "symptom": "Cash drawer not opening after BillFree integration (opens fine on direct / native print)",
      "cause": "BillFree captures the POS print as XPS (a graphical format) and forwards a rendered copy to the thermal printer. Raw ESC/POS control codes embedded in the original print — including the cash-drawer 'kick' (ESC p / 1B 70) — are not preserved in XPS, so the forwarded print never triggers the drawer. Direct (non-BillFree) printing kept those codes, which is why the drawer opened before. The drawer must therefore be opened at the printer-driver level so it fires on the forwarded job.",
      "solution": [
        "Fix (confirmed): open the cash drawer at the printer-driver level so it fires on every forwarded print, independent of any POS command.",
        "Control Panel > Devices and Printers > right-click the thermal printer (e.g. POS-80) > Printer Properties.",
        "Advanced tab > 'Printing Defaults...' — set it HERE (device-level). BillFree forwards from a background context that uses Printing Defaults, not the current user's Printing Preferences; setting it only in Preferences is the usual reason it still fails.",
        "Open the Peripheral / Cash Drawer tab > set 'Open Drawer #1: After printing' (or Before printing) > Apply. Repeat the same in Printing Preferences for safety.",
        "Confirm BillFree's Forward Print target is this exact thermal printer (the one wired to the drawer) — not the HP/BillFree virtual printer or any other printer.",
        "Test a bill via 'BillFree + Print' — the drawer should now open.",
        "If the Cash Drawer / Peripheral tab is missing: a generic driver is installed. Install the proper 80mm thermal driver (which exposes a Peripheral/Cash Drawer tab), then repeat.",
        "POS-provider note: no change is needed on the POS side if they use the default Windows print path and rely on the driver's cash-drawer property (most do). Only if the POS sends a custom direct-port kick must they target the physical printer port directly, outside the BillFree/XPS path."
      ],
      "tags": [
        "cash drawer",
        "drawer",
        "cash-drawer",
        "open drawer after printing",
        "pos-80",
        "pos 80",
        "thermal printer",
        "esc/pos",
        "drawer kick",
        "printing defaults",
        "forward print",
        "printer driver",
        "universal",
        "restaurant pos",
        "dart"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-06",
      "visibility": "public",
      "related": [
        "setup-printing-types",
        "popup-delivery-options",
        "setup-universal",
        "ci-printer-props"
      ]
    },
    {
      "id": "ci-pagesize-a4a5",
      "category": "Common Issue",
      "system": "Printer",
      "type": "printing",
      "symptom": "A4 invoice prints fine directly from POS but is misaligned / cut / distorted when routed through BillFree (POS format A4, customer paper A5)",
      "cause": "BillFree's virtual printer intercepts the print job and processes it based on ITS OWN configured page size. If the BillFree printer is set to A5 (to match the physical paper) while the POS invoice format is A4, BillFree tries to scale/squeeze the A4 layout into A5 during interception — causing misalignment, cutting, or distortion. Printing directly from the POS works because no interception/rescaling happens.",
      "solution": [
        "Fix = split page-size configuration: the BillFree virtual printer must match the POS invoice FORMAT, while the physical printer matches the actual PAPER.",
        "Set the BillFree virtual printer page size to A4 — it MUST match the POS invoice/bill format so the bill is captured accurately, with no scaling at interception. (Devices and Printers > BillFree printer > Printing Preferences/Properties > Page Size = A4.)",
        "Keep the physical customer printer set to A5 (its real paper size). The printer hardware then does the final A4 -> A5 scaling and produces a correct A5 print.",
        "Quick reference -> POS Invoice Format: A4 | BillFree Virtual Printer Page Size: A4 (match POS format) | Physical Customer Printer Page Size: A5 (actual paper).",
        "Rule of thumb: BillFree's page size always matches the POS invoice FORMAT (not the paper); the physical printer matches the PAPER. A mismatch at the BillFree layer is what breaks the layout.",
        "Verify: print a test bill via 'BillFree + Print' and confirm alignment is correct on the A5 output."
      ],
      "tags": [
        "a4",
        "a5",
        "paper size",
        "page size",
        "pagesize",
        "scaling",
        "misalignment",
        "cut",
        "cutting",
        "distortion",
        "invoice format",
        "bill format",
        "virtual printer",
        "page setup",
        "printing"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-06",
      "visibility": "public",
      "related": [
        "setup-config-popup",
        "setup-printing-types",
        "ci-a5-portrait",
        "marg-a4instead3",
        "ci-pagesize-a5",
        "ci-print-cutoff"
      ]
    },
    {
      "id": "ci-pagesize-a5",
      "category": "Common Issue",
      "system": "Printer",
      "type": "printing",
      "symptom": "A5 invoice format prints incorrectly / fails via BillFree (clipping, rotation, truncation) unless both BillFree and the physical printer have the correct multi-level page-size settings",
      "cause": "An A5 invoice routed through BillFree needs the page size set at TWO levels on BOTH printers: the General (main) page size = A5, and the Advanced / Capture (logical) page size = A4. If the Advanced/Capture size is left wrong (or only the General size is set), BillFree captures or scales the bill incorrectly, producing clipping, rotation, or truncation on the A5 output.",
      "solution": [
        "An A5 invoice through BillFree must be configured at two levels on BOTH the BillFree virtual printer AND the physical printer — General page size = A5, Advanced/Capture (logical) page size = A4.",
        "Reference -> POS: A5 | BillFree virtual printer: General A5, Advanced/Capture A4 | Physical customer printer: General A5, Advanced/Capture A4.",
        "On the merchant PC, open Printer Properties > BillFree Printer > General tab > set Page Size = A5.",
        "In BillFree Printer > Advanced (or Device Settings) tab > set the capture / logical page size = A4.",
        "Open the Physical Customer Printer properties > General tab > set Page Size = A5.",
        "In the Physical Printer > Advanced tab > set the capture / logical page size = A4.",
        "Save settings and reboot the BillFree service (or ask the merchant to run BillFree Reset) if needed.",
        "Print a test invoice from the POS and confirm correct output on A5 paper (no clipping, rotation, or truncation).",
        "Document the result in the ticket and attach a photo of the printed A5 bill."
      ],
      "tags": [
        "a5",
        "a4",
        "page size",
        "pagesize",
        "general tab",
        "advanced tab",
        "capture",
        "logical page size",
        "device settings",
        "clipping",
        "rotation",
        "truncation",
        "invoice format",
        "billfree reset",
        "printing"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-06",
      "visibility": "public",
      "related": [
        "ci-pagesize-a4a5",
        "setup-config-popup",
        "setup-printing-types",
        "ci-a5-portrait",
        "ci-print-cutoff"
      ]
    },
    {
      "id": "ci-print-cutoff",
      "category": "Common Issue",
      "system": "Printer",
      "type": "printing",
      "symptom": "Invoice (A4 or A5) printed via BillFree is cut off at the bottom — some content missing — even though the POS and printer report the correct page size",
      "cause": "The printer's effective printable area is slightly smaller than the document layout expects, so the last lines of the bill fall outside the printable region and get clipped. The page size 'matches' on paper, but the usable print area does not fully cover the document height.",
      "solution": [
        "Fix = create or select a CUSTOM paper size with a slightly increased length (height) so the document content fits within the printable region.",
        "Add the custom size via Print Server Properties (Control Panel > Devices and Printers > select any printer > Print Server Properties > Forms tab > tick 'Create a new form', name it, set the size) — or via the printer's Windows Printer Properties.",
        "Example custom sizes -> A4 standard: 8.27 x 11.69 in | A4 extended (custom): 8.27 x 11.80 in (adds ~0.11 in to prevent the bottom cut).",
        "For A5, apply a similar small increase to the height (e.g. A5 height + 0.10 to 0.15 in).",
        "Select this custom paper size on BOTH the BillFree virtual printer and the physical printer (and in the POS print format if it lets you pick the paper).",
        "Print a test invoice and confirm the full bill prints with no bottom cut-off; adjust the extra height slightly if a little content still clips."
      ],
      "tags": [
        "bottom cut",
        "cut off",
        "cutoff",
        "cut at bottom",
        "custom paper size",
        "printable area",
        "form",
        "print server",
        "a4",
        "a5",
        "margin",
        "truncated",
        "missing content",
        "height",
        "printing"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-06",
      "visibility": "public",
      "related": [
        "ci-pagesize-a4a5",
        "ci-pagesize-a5",
        "setup-config-popup"
      ]
    },
    {
      "id": "ci-0x709",
      "category": "Common Issue",
      "system": "Printer",
      "type": "error",
      "symptom": "Error 0x00000709 'Operation could not be completed. Double check the printer's name...'",
      "cause": "Corrupted registry entry for the default printer.",
      "solution": [
        "Open regedit as Administrator.",
        "Navigate to HKEY_CURRENT_USER\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows.",
        "Right-click the 'Windows' key > Permissions.",
        "Select the user, grant Full Control, OK.",
        "Restart and try setting the default printer again."
      ],
      "tags": [
        "printer",
        "0x00000709",
        "registry",
        "default printer"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "ci-notdeliver-nodata",
      "category": "Common Issue",
      "system": "Delivery",
      "type": "error",
      "symptom": "Bills not delivering to BillFree — bills NOT uploading from Data folder",
      "cause": "Antivirus/firewall block, file permissions, or inactive MID.",
      "solution": [
        "Cause 1 (AV/firewall): add allow rules for C:\\BillFree\\BillFree.exe and the C:\\BillFree\\Data folder.",
        "Cause 2 (permissions): right-click BillFree.exe and the Data folder > Properties > Security > ensure 'Users' group has Full Control.",
        "Cause 3 (inactive MID): confirm in backend that the merchant's MID is Active and configured."
      ],
      "tags": [
        "delivery",
        "upload",
        "antivirus",
        "permissions",
        "mid",
        "data folder"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "ci-notdeliver-data"
      ]
    },
    {
      "id": "ci-notdeliver-data",
      "category": "Common Issue",
      "system": "Delivery",
      "type": "error",
      "symptom": "Bills not delivering to BillFree — bills ARE uploading from Data folder",
      "cause": "Large PDF size (upload timeout) or wrong POS configured in backend (L2: needs log/backend analysis if steps below don't resolve).",
      "solution": [
        "Cause 4 (large PDF): check C:\\BillFree\\Data; large multi-MB PDFs (often a high-res logo) cause timeouts. Ask merchant to use a smaller optimized image.",
        "Cause 5 (wrong POS in backend): verify backend POS type matches reality (e.g. set to Tally but using Busy)."
      ],
      "tags": [
        "delivery",
        "timeout",
        "pdf size",
        "logo",
        "backend pos"
      ],
      "level": "L2",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "ci-notdeliver-nodata"
      ]
    },
    {
      "id": "ci-popup-missing",
      "category": "Common Issue",
      "system": "Delivery",
      "type": "error",
      "symptom": "BillFree popup not appearing after saving a bill",
      "cause": "Service stuck, AV quarantine, wrong printer, inactive MID, or Tally TDL not loaded.",
      "solution": [
        "Cause 1 (service stuck): restart the PC first; if recurring, do a BillFree reset (re-run setup).",
        "Cause 2 (AV quarantine): check antivirus quarantine/blocked log, restore BillFree.exe, add permanent exception.",
        "Cause 3 (wrong printer): ensure POS isn't printing to the physical printer; set default invoice printer to BillFree in Tally/Busy/Marg.",
        "Cause 4 (inactive MID): confirm MID is Active in backend.",
        "Cause 5 (Tally TDL): ensure the TDL is loaded and active (see Tally API section)."
      ],
      "tags": [
        "popup",
        "missing",
        "service",
        "quarantine",
        "printer",
        "mid",
        "tdl",
        "no popup",
        "popup not coming",
        "mobile number",
        "enter mobile number",
        "bill saved",
        "after saving bill"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "setup-printing-types"
      ]
    },
    {
      "id": "ci-a5-portrait",
      "category": "Common Issue",
      "system": "Printing",
      "type": "printing",
      "symptom": "Web POS on Chrome using A5 landscape, but digital bill shows A5 portrait",
      "cause": "Browser rendering/config issue.",
      "solution": [
        "Try the same on Firefox browser — this usually fixes it.",
        "In some cases it's also a config issue on the Firefox browser side."
      ],
      "tags": [
        "a5",
        "landscape",
        "portrait",
        "chrome",
        "firefox",
        "web pos"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "ci-pagesize-a4a5",
        "ci-pagesize-a5"
      ]
    },
    {
      "id": "ci-mfp-noprint",
      "category": "Common Issue",
      "system": "Printing",
      "type": "error",
      "symptom": "Print not coming — file forwarding to customer's printer but not printing (MFP printer)",
      "cause": "Borderless/paper type setting on MFP.",
      "solution": [
        "In BillFree printer properties click Borderless.",
        "Select HP Photo Papers as Paper Type on both the General and Advanced tabs."
      ],
      "tags": [
        "mfp",
        "print",
        "borderless",
        "hp photo papers",
        "forward"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/ci-mfp-noprint-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "marg-leftcut"
      ]
    },
    {
      "id": "ci-rightcut",
      "category": "Common Issue",
      "system": "Printing",
      "type": "error",
      "symptom": "Print is coming but cutting from the right side",
      "cause": "AutoPrintMode setting.",
      "solution": [
        "Set AutoPrintMode = NO/false in the comp during BillFree configuration. This works in most cases."
      ],
      "tags": [
        "print",
        "right cut",
        "autoprintmode",
        "comp"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/ci-rightcut-1.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "ci-scaling",
      "category": "Common Issue",
      "system": "Display",
      "type": "error",
      "symptom": "BillFree popup not showing properly due to display scaling",
      "cause": "High DPI scaling (125/150/175%).",
      "solution": [
        "Right-click Desktop > Display settings > check Scale and layout %.",
        "Navigate to C:\\BillFree\\Bill_Free.exe.",
        "Right-click Bill_Free.exe > Properties > Compatibility tab.",
        "Click 'Change high DPI settings'.",
        "Check 'Override high DPI scaling behavior. Scaling performed by:' and select 'System (Enhanced)' or 'Application'.",
        "OK > Apply > restart PC or the BillFree utility."
      ],
      "tags": [
        "scaling",
        "dpi",
        "popup",
        "display",
        "compatibility"
      ],
      "level": "L1",
      "images": [
        {
          "src": "kb-images/ci-scaling-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/ci-scaling-2.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "ci-rdp",
      "category": "Common Issue",
      "system": "RDP",
      "type": "error",
      "level": "L2",
      "symptom": "Printer redirection / config issues (invalid or 0 KB files) in Client-Server (RDP) setup",
      "cause": "Printers not redirected from client to remote session.",
      "solution": [
        "Install TSPrint server on the server side: https://www.terminalworks.com/downloads/tsprint/3.2.3.13/TSPrint_server.exe",
        "Install TSPrint client on the client side: https://www.terminalworks.com/downloads/tsprint/TSPrint_client.exe",
        "Redirection sends printers from the client's local workstation into the remote session."
      ],
      "tags": [
        "rdp",
        "tsprint",
        "redirection",
        "client-server",
        "0kb"
      ],
      "images": [
        {
          "src": "kb-images/ci-rdp-1.jpg",
          "caption": ""
        },
        {
          "src": "kb-images/ci-rdp-2.jpg",
          "caption": ""
        }
      ],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "appendix-escalation",
      "category": "Reference",
      "system": "Escalation",
      "type": "reference",
      "symptom": "Escalation matrix — when to escalate L1 / L2 / L3",
      "cause": "Tiered support model.",
      "solution": [
        "L1 Support Agent: configuration, setup, known issues. Resolve using this KB.",
        "L2 Senior Support: complex issues, log analysis, backend changes. Collect logs, MID, OS details; escalate with a detailed summary.",
        "L3 Engineering: software bugs, crashes, server-side delivery failures. File a bug report with full repro steps.",
        "Required for escalation: MID, POS name+version, Windows OS version+architecture, BillFree utility version, logs from C:\\BillFree\\Logs\\, error screenshots, repro steps."
      ],
      "tags": [
        "escalation",
        "l1",
        "l2",
        "l3",
        "bug report"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "internal"
    },
    {
      "id": "appendix-checklist",
      "category": "Reference",
      "system": "Verification",
      "type": "reference",
      "symptom": "Universal verification checklist (run before troubleshooting)",
      "cause": "Baseline health check.",
      "solution": [
        "BillFree utility is running — check system tray icon.",
        "BillFree printer is installed — check Devices and Printers.",
        "BillFree printer is selected as default in the POS software.",
        "Test print triggers the BillFree popup.",
        "PDF + JSON files appear in C:\\BillFree\\Data\\.",
        "Files upload successfully — Data folder empties after a few seconds.",
        "Customer receives the digital bill via WhatsApp or SMS."
      ],
      "tags": [
        "checklist",
        "verification",
        "baseline",
        "health"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public",
      "related": [
        "setup-universal"
      ]
    },
    {
      "id": "appendix-glossary",
      "category": "Reference",
      "system": "Glossary",
      "type": "reference",
      "symptom": "Glossary of BillFree terms",
      "cause": "Terminology reference.",
      "solution": [
        "MID: Merchant ID, unique identifier assigned during registration.",
        "Auth Token: unique authentication key for API integrations, per merchant.",
        "TDL: Tally Definition Language, scripting language for Tally ERP/Prime.",
        "XPS: XML Paper Specification, Windows document format intercepted by BillFree.",
        "DMP: Dot Matrix Printer, raw text printing mode.",
        "BillTransfer: BillFree utility for direct Tally integration without a virtual printer.",
        ".comp: BillFree config file storing MID, printer name, settings (universal setup).",
        "config.ini: parsing rules file defining how invoice fields are extracted.",
        "RDP: Remote Desktop Protocol, used for client-server setups.",
        "TSPrint: third-party printer redirection tool for RDP.",
        "POS: Point of Sale, the merchant's billing/invoicing software."
      ],
      "tags": [
        "glossary",
        "terms",
        "definitions"
      ],
      "level": "L1",
      "images": [],
      "last_verified": "2026-05",
      "visibility": "public"
    },
    {
      "id": "ci-qr-forward-blank",
      "category": "Common Issue",
      "system": "Printing",
      "type": "error",
      "symptom": "QR / UPI 2D code prints blank via BillFree Forward Print, but prints fine when printing directly on the merchant's own printer",
      "cause": "The QR is a DYNAMIC IMAGE the POS writes per bill and Crystal Reports loads by file name at render time (e.g. UPIQRCodeImageName in a Marg .rpt). BillFree captures the job correctly (the QR DOES appear on the WhatsApp digital bill), but its Forward Print step re-renders / re-spools to the physical printer and the per-bill QR image is gone by then, so it prints blank. A linear barcode on the same receipt keeps printing because it is a FONT (e.g. IDAutomation) with no file dependency. On a THERMAL printer the tell is sharper: fonts print but images drop = the job is going out in text mode, not raster.",
      "solution": [
        "Confirm the pattern: a linear barcode still prints but the QR/2D code is blank ONLY through BillFree Forward Print. That means the QR is a dynamic image, not a font.",
        "Check the WhatsApp digital bill BillFree sent. If the QR IS on the digital bill, BillFree captured it correctly and the loss is purely in the forward-to-printer step (this is the common case).",
        "First try IF the option exists: set the BillFree / forward-target printer to 'Print as image' / render as bitmap (Printer Properties > Advanced). NOTE: most thermal drivers (e.g. POS-80C) and many Brother/HP drivers do NOT expose this option - if it is not there, skip it.",
        "Robust fix - stop relying on the lossy forward. Printing DIRECTLY from the POS already produces a perfect receipt (QR included), so print the paper copy straight from the POS to the physical printer, and capture the digital bill through a NON-print path. For Marg specifically, switch to the Marg BillFree API integration (see marg-api) instead of the virtual printer + forward. This removes the re-render entirely and is a cleaner integration.",
        "If Forward Print must stay: when the physical printer is a thermal (e.g. POS-80C), set it to graphics/raster mode, NOT text-only - fonts printing while the QR image drops is the classic text-mode symptom. Also, if BillFree can forward/reprint its GENERATED PDF (the same one used for the digital bill, which already has the QR) instead of re-spooling the raw job, use that.",
        "Do NOT edit the .rpt to embed the QR - a per-bill UPI QR is dynamic and cannot be made static. The fix is always in the print / forward path, not the report."
      ],
      "tags": [
        "qr",
        "qr code",
        "upi",
        "upi qr",
        "2d code",
        "barcode blank",
        "blank qr",
        "forward print",
        "forwarded printer",
        "print as image",
        "marg",
        "crystal report",
        "rpt",
        "not printing"
      ],
      "level": "L1",
      "last_verified": "2026-07",
      "visibility": "public",
      "related": [
        "setup-config-popup",
        "setup-printing-types",
        "marg-leftcut",
        "marg-api"
      ]
    },
    {
      "id": "tally-bitmap-mode",
      "category": "POS Integration",
      "system": "Tally",
      "type": "error",
      "symptom": "Tally (Universal) bill is not readable / not parsing - the whole invoice comes through as an image, so BillFree can't auto-read the mobile number or fields",
      "cause": "In Tally Prime's Print Configuration, 'Use Bitmap Mode to print' is set to Yes. Bitmap mode sends the invoice to the printer as a flat raster IMAGE instead of selectable text, so the BillFree Universal virtual printer captures a picture with no readable text fields (mobile number, amount, items) to parse.",
      "solution": [
        "In Tally Prime, open the invoice and press Ctrl+P (Print), or open Print Preview.",
        "On the print menu choose P: Print > Configuration (Print Configuration opens).",
        "In 'List of Configurations', scroll to the 'Advanced Configurations' section and find 'Use Bitmap Mode to print' (it will show Yes).",
        "Set 'Use Bitmap Mode to print' to No.",
        "Accept / save the configuration, then reprint the bill to the BillFree printer. The invoice now goes as text and BillFree can read the fields (mobile number, amount) again."
      ],
      "tags": [
        "tally",
        "tally universal",
        "bitmap mode",
        "use bitmap mode to print",
        "not readable",
        "image",
        "not parsing",
        "mobile not reading",
        "auto read",
        "print configuration",
        "field not captured",
        "blank data",
        "format issue"
      ],
      "level": "L1",
      "last_verified": "2026-07",
      "visibility": "public",
      "related": [
        "setup-printing-types",
        "setup-universal",
        "tally-select-printer"
      ]
    }
  ],
  "schema": {
    "fields": [
      "id",
      "category",
      "system",
      "type",
      "symptom",
      "cause",
      "solution",
      "tags",
      "level",
      "images",
      "last_verified",
      "visibility",
      "related"
    ],
    "notes": "id is immutable (join key for AI matches, deep links, feedback). last_verified=YYYY-MM. visibility: public|internal."
  }
};
